autocmd!

syntax enable

filetype off
set nocompatible

" Vundle stuff
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Github stuff
Plugin 'kien/ctrlp.vim'
"Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'tpope/vim-surround'
Bundle 'powerline/powerline'

call vundle#end()

set t_Co=256

set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
let g:Powerline_symbols = "fancy"

set background=light
if has('gui_running')
    "colorscheme solarized
    colorscheme irblack
else
    "colorscheme solarized
    colorscheme irblack
endif


filetype plugin indent on

set laststatus=2
set noshowmode
set history=25
set showmode
set showcmd
set expandtab
set backspace=2
set tabstop=4
set ruler
set softtabstop=4
set shiftwidth=4

if version >= 700
   set showtabline=1
endif
set nolist
set nomodeline
set nowrap
set autoindent
set formatoptions-=u
"set textwidth=79
set encoding=utf-8
set fileformats=unix,dos
set fileformat=unix
set fileencodings=ucs-bom,utf-8,default,latin1
set fileencoding=utf-8
set shellslash
"set noinsertmode

"filetype plugin indent on

autocmd FileType c,cpp,slang,cxx,h,hpp,hxx set cindent softtabstop=4 tabstop=4 shiftwidth=4 expandtab 
autocmd FileType c set formatoptions+=ro
autocmd FileType perl,pl set smartindent
autocmd FileType py set smartindent
autocmd FileType css set smartindent
autocmd FileType html,css set noexpandtab tabstop=2
autocmd FileType java set smartindent
autocmd FileType make set noexpandtab shiftwidth=8
autocmd FileType scala,js set smartindent tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType clj set smartindent tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType rb set smartindent tabstop=2 softtabstop=2 shiftwidth=2 expandtab

set ignorecase
set smartcase

set incsearch

abbreviate teh the
abbreviate bsae base

" The following takes care of rainbow_parentheses
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

"nmap <Esc> <Nop>
